version: '3.3'

services:
  test:
    build:
      context: ..
      dockerfile: docker/Dockerfile.test
    image: ${IMAGE:-test}
    links:
      - mongo
      - elasticsearch
      - prometheus
      - pushgateway
    
    environment:
      - MONGO_SERVICE_HOST=mongo
      - MONGO_SERVICE_PORT=27017
      - MONGO_DB=test

      - PROMETHEUS_SERVICE_HOST=prometheus
      - PROMETHEUS_SERVICE_PORT=9090

      - PUSHGATEWAY_METRICS_SERVICE_HOST=pushgateway
      - PUSHGATEWAY_METRICS_SERVICE_PORT=9091
      - PUSHGATEWAY_METRICS_ENABLED=true

      - ELASTICSEARCH_LOGGING_ENABLED=true
      - ELASTICSEARCH_SERVICE_HOST=elasticsearch
      - ELASTICSEARCH_SERVICE_PORT=9200

  mongo:
    image: mongo:latest
  
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      # - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ulimits:
      memlock:
        soft: -1
        hard: -1

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway