---
    # Container descriptor
    - descriptor: "pip-services:context-info:default:default:1.0"
      name: "beacons"
      description: "Beacons microservice"
    
    # Console logger
    - descriptor: "pip-services:logger:console:default:1.0"
      level: "trace"
    
    # Perfomance counter that post values to log
    - descriptor: "pip-services:counters:log:default:1.0"
    
    {{#if MEMORY_ENABLED}}
    # In-memory persistence. Use only for testing!
    - descriptor: "beacons:persistence:memory:default:1.0"
    {{/if}}
    
    {{#if FILE_ENABLED}}
    # File persistence
    - descriptor: "beacons:persistence:file:default:1.0"
      path: {{FILE_PATH}}{{#unless FILE_PATH}}"./data/beacons.json"{{/unless}}
    {{/if}}
    
    {{#if MONGO_ENABLED}}
    # MongoDb persistence
    - descriptor: "beacons:persistence:mongodb:default:1.0"
      connection:
        uri: {{MONGO_SERVICE_URI}}
        host: {{MONGO_SERVICE_HOST}}{{#unless MONGO_SERVICE_HOST}}"localhost"{{/unless}}
        port: {{MONGO_SERVICE_PORT}}{{#unless MONGO_SERVICE_PORT}}27017{{/unless}}
        database: {{MONGO_DB}}{{#unless MONGO_DB}}"test"{{/unless}}
    {{/if}}
    
    {{#if COUCHBASE_ENABLED}}
    # Couchbase Persistence
    - descriptor: "beacons:persistence:couchbase:default:1.0"
      bucket: {{COUCHBASE_BUCKET}}{{#unless COUCHBASE_BUCKET}}test{{/unless}}
      connection:
        uri: {{{COUCHBASE_SERVICE_URI}}}
        host: {{{COUCHBASE_SERVICE_HOST}}}{{#unless COUCHBASE_SERVICE_HOST}}localhost{{/unless}}
        port: {{COUCHBASE_SERVICE_PORT}}{{#unless COUCHBASE_SERVICE_PORT}}8091{{/unless}}
      credential:
        username: {{COUCHBASE_USER}}{{#unless COUCHBASE_USER}}Administrator{{/unless}}
        password: {{COUCHBASE_PASS}}{{#unless COUCHBASE_PASS}}password{{/unless}}
    {{/if}}
    
    {{#unless MEMORY_ENABLED}}{{#unless FILE_ENABLED}}{{#unless MONGO_ENABLED}}{{#unless COUCHBASE_ENABLED}}
    # Default to in-memory persistence, if nothing is set
    - descriptor: "beacons:persistence:memory:default:1.0"
    {{/unless}}{{/unless}}{{/unless}}{{/unless}}
    
    # Controller
    - descriptor: "beacons:controller:default:default:1.0"
    
    {{#if HTTP_ENABLED}}
    # Common HTTP endpoint
    - descriptor: "pip-services:endpoint:http:default:1.0"
      connection:
        protocol: http
        host: 0.0.0.0
        port: {{HTTP_PORT}}{{#unless HTTP_PORT}}8080{{/unless}}
    
    # HTTP endpoint service version 1.0
    - descriptor: "beacons:service:commandable-http:default:1.0"
    
    # Hearbeat service
    - descriptor: "pip-services:heartbeat-service:http:default:1.0"
    
    # Status service
    - descriptor: "pip-services:status-service:http:default:1.0"
    {{/if}}
    
    {{#if GRPC_ENABLED}}
    # Common GRPC endpoint
    - descriptor: "beacons:endpoint:grpc:default:1.0"
      connection:
        protocol: http
        host: 0.0.0.0
        port: 8090
    
    # GRPC endpoint service version 1.0
    - descriptor: "beacons:service:grpc:default:1.0"
    
    # Commandable GRPC endpoint version 1.0
    - descriptor: "beacons:service:commandable-grpc:default:1.0"
    {{/if}}