---
# Container descriptor
- descriptor: "pip-services:context-info:default:default:1.0"
  name: "beacons"
  description: "Beacons microservice"

# Console logger
- descriptor: "pip-services:logger:console:default:1.0"
  level: "trace"

# Perfomance counter that post values to log
- descriptor: "pip-services:counters:log:default:1.0"

{{#MEMORY_ENABLED}}
# In-memory persistence. Use only for testing!
- descriptor: "beacons:persistence:memory:default:1.0"
{{/MEMORY_ENABLED}}

{{#FILE_ENABLED}}
# File persistence
- descriptor: "beacons:persistence:file:default:1.0"
  path: {{FILE_PATH}}{{^FILE_PATH}}"./data/beacons.json"{{/FILE_PATH}}
{{/FILE_ENABLED}}
    
{{#MONGO_ENABLED}}
# MongoDb persistence
- descriptor: "beacons:persistence:mongodb:default:1.0"
    connection:
      uri: {{MONGO_SERVICE_URI}}
      host: {{MONGO_SERVICE_HOST}}{{^MONGO_SERVICE_HOST}}"localhost"{{/MONGO_SERVICE_HOST}}
      port: {{MONGO_SERVICE_PORT}}{{^MONGO_SERVICE_PORT}}27017{{/MONGO_SERVICE_PORT}}
      database: {{MONGO_DB}}{{^MONGO_DB}}"test"{{/MONGO_DB}}
{{/MONGO_ENABLED}}

{{^MEMORY_ENABLED}}{{^FILE_ENABLED}}{{^MONGO_ENABLED}}
# In-memory persistence. Use only for testing!
- descriptor: "beacons:persistence:memory:default:1.0"
{{/MONGO_ENABLED}}{{/FILE_ENABLED}}{{/MEMORY_ENABLED}}

# Controller
- descriptor: "beacons:controller:default:default:1.0"

# Common HTTP endpoint
- descriptor: "pip-services:endpoint:http:default:1.0"
  connection:
    protocol: http
    host: 0.0.0.0
    port: {{HTTP_PORT}}{{^HTTP_PORT}}8080{{/HTTP_PORT}}

# HTTP endpoint service version 1.0
- descriptor: "beacons:service:commandable-http:default:1.0"

# Hearbeat service
- descriptor: "pip-services:heartbeat-service:http:default:1.0"

# Status service
- descriptor: "pip-services:status-service:http:default:1.0"

{{#GRPC_ENABLED}}
# Common GRPC endpoint
- descriptor: "beacons:endpoint:grpc:default:1.0"
  connection:
    protocol: http
    host: 0.0.0.0
    port: 8090
    
# GRPC endpoint service version 1.0
- descriptor: "beacons:service:grpc:default:1.0"
  
# Commandable GRPC endpoint version 1.0
- descriptor: "beacons:service:commandable-grpc:default:1.0"
{{/GRPC_ENABLED}}